/** @deprecated use @/lib/bodyOrbit */
export {
  ORBIT_INACTIVITY_SEC,
  ORBIT_VISUAL_TIME_SCALE,
  captureOrbitFrame,
  circularOrbitAngularSpeed,
  clampOrbitRadius,
  defaultOrbitFrame,
  defaultOrbitRadius,
  distanceToBodyCenter,
  distanceToBodyCenter as distanceToEarthCenter,
  formatOrbitZoneKm,
  GRAVITY_BODY_IDS,
  isWithinOrbitZone,
  orbitPositionAtPhase,
  orbitZoneMax,
  orbitZoneMax as ORBIT_ZONE_MAX,
  orbitZoneMin,
  orbitZoneMin as ORBIT_ZONE_MIN,
  defaultOrbitRadius as ORBIT_DEFAULT_RADIUS,
  type OrbitFrame,
} from "@/lib/bodyOrbit";
