import type { Metadata } from "next";
import type { ReactNode } from "react";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy — Orbit",
  description:
    "How Orbit (planets.ooo) and the Orbit Screensaver Chrome extension handle data, Premium checkout, and local storage.",
};

const LAST_UPDATED = "June 16, 2026";

function Section({
  title,
  children,
}: {
  title: string;
  children: ReactNode;
}) {
  return (
    <section className="mt-10">
      <h2 className="text-lg font-semibold tracking-tight text-zinc-100">
        {title}
      </h2>
      <div className="mt-3 space-y-3 text-sm leading-7 text-zinc-400">
        {children}
      </div>
    </section>
  );
}

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-[#030508] px-6 py-10 text-zinc-200">
      <article className="mx-auto max-w-2xl pb-16">
        <p className="mb-3 font-mono text-xs uppercase tracking-[0.35em] text-sky-300/60">
          Orbit · planets.ooo
        </p>
        <h1 className="text-4xl font-semibold tracking-tight text-zinc-50 sm:text-5xl">
          Privacy Policy
        </h1>
        <p className="mt-4 text-sm text-zinc-500">Last updated: {LAST_UPDATED}</p>
        <p className="mt-6 text-sm leading-7 text-zinc-400">
          This policy describes how the Orbit solar system explorer website (
          <a
            href="https://www.planets.ooo"
            className="text-sky-300/90 underline decoration-sky-300/30 underline-offset-2 hover:text-sky-200"
          >
            planets.ooo
          </a>
          ) and the <strong className="font-medium text-zinc-300">Orbit Screensaver</strong>{" "}
          Chrome extension collect, use, and store information. We designed both
          products to work without a user account.
        </p>

        <Section title="Summary">
          <p>
            The screensaver extension stores your preferences and Premium unlock
            locally in Chrome. Premium checkout is processed by Stripe on
            planets.ooo; we do not receive or store card numbers. The website
            may call public NASA/JPL APIs for planetary facts. Optional AI
            features on the website send prompts to xAI only when you use them
            and only if the site operator has configured an API key.
          </p>
          <p>
            We do not sell personal information. We do not use advertising or
            social-media trackers in the extension or on the core explorer.
          </p>
        </Section>

        <Section title="Chrome extension (Orbit Screensaver)">
          <p>Data stored locally on your device via Chrome extension storage:</p>
          <ul className="list-disc space-y-2 pl-5">
            <li>
              <strong className="text-zinc-300">Settings</strong> — idle timeout,
              enabled state, display selection, flight/exit key choices (
              <code className="text-zinc-300">chrome.storage.sync</code>)
            </li>
            <li>
              <strong className="text-zinc-300">Premium status</strong> — a
              signed unlock token and a per-install identifier (
              <code className="text-zinc-300">chrome.storage.local</code>)
            </li>
            <li>
              <strong className="text-zinc-300">Debug metadata</strong> — last
              screensaver run status (local only, for troubleshooting)
            </li>
          </ul>
          <p>
            This data stays on your device unless you use Premium checkout (see
            below). Uninstalling the extension removes locally stored extension
            data. Chrome may sync settings across signed-in devices if you have
            Chrome Sync enabled for extensions.
          </p>
          <p>
            The extension requests permission to detect idle state, read tab
            information for screensaver windows, access display layout, and load
            content from planets.ooo when the online scenic tour is used.
          </p>
        </Section>

        <Section title="Premium purchase (Stripe)">
          <p>
            Premium is a one-time purchase completed on planets.ooo through{" "}
            <a
              href="https://stripe.com/privacy"
              className="text-sky-300/90 underline decoration-sky-300/30 underline-offset-2 hover:text-sky-200"
              rel="noopener noreferrer"
              target="_blank"
            >
              Stripe Checkout
            </a>
            . When you buy Premium, we send Stripe:
          </p>
          <ul className="list-disc space-y-2 pl-5">
            <li>Your Chrome extension ID</li>
            <li>A random install ID generated by the extension</li>
            <li>Product metadata (Orbit Premium)</li>
          </ul>
          <p>
            Stripe processes payment and may collect billing details according
            to its own privacy policy. We receive confirmation that payment
            succeeded and issue a signed entitlement token bound to your
            extension ID and install ID. We do not store full payment card
            numbers on planets.ooo.
          </p>
        </Section>

        <Section title="Website (planets.ooo explorer)">
          <p>
            The web explorer runs in your browser. Standard hosting logs (IP
            address, user agent, request time) may be retained briefly by our
            hosting provider for security and reliability.
          </p>
          <p>
            <strong className="text-zinc-300">NASA / JPL data</strong> — Server
            routes may fetch public planetary data from NASA/JPL Horizons and
            related NASA sources. These requests use planet identifiers, not
            personal information about you.
          </p>
          <p>
            <strong className="text-zinc-300">Optional AI guide & Imagine</strong>{" "}
            — If enabled by the site operator, flight-guide and transit-effect
            features send your prompts and limited flight context to xAI&apos;s API.
            Do not enter passwords or sensitive personal data into AI prompts.
            AI features are optional and not required for the screensaver.
          </p>
        </Section>

        <Section title="What we do not collect">
          <ul className="list-disc space-y-2 pl-5">
            <li>No Orbit user accounts or passwords</li>
            <li>No sale of personal information</li>
            <li>
              No advertising trackers in the extension package we distribute
            </li>
            <li>
              No collection of browsing history outside planets.ooo screensaver
              pages and the extension&apos;s own pages
            </li>
          </ul>
        </Section>

        <Section title="Third-party services">
          <ul className="list-disc space-y-2 pl-5">
            <li>
              <strong className="text-zinc-300">Google Chrome</strong> — extension
              distribution, storage APIs, and Web Store policies
            </li>
            <li>
              <strong className="text-zinc-300">Stripe</strong> — payment processing
            </li>
            <li>
              <strong className="text-zinc-300">Vercel</strong> — website hosting
            </li>
            <li>
              <strong className="text-zinc-300">NASA / JPL</strong> — public
              ephemeris and science data
            </li>
            <li>
              <strong className="text-zinc-300">xAI</strong> — optional AI features
              on the website only, when configured
            </li>
          </ul>
        </Section>

        <Section title="Children">
          <p>
            Orbit is not directed at children under 13. We do not knowingly
            collect personal information from children.
          </p>
        </Section>

        <Section title="Your choices">
          <ul className="list-disc space-y-2 pl-5">
            <li>Disable or uninstall the extension at any time in Chrome</li>
            <li>Adjust screensaver settings in the extension popup</li>
            <li>Decline Premium purchase — Basic scenic mode remains available</li>
            <li>Disable Chrome Sync for extensions if you do not want settings synced</li>
          </ul>
        </Section>

        <Section title="Changes">
          <p>
            We may update this policy when features or legal requirements change.
            The &quot;Last updated&quot; date at the top will reflect the latest
            revision. Continued use after changes constitutes acceptance of the
            updated policy.
          </p>
        </Section>

        <Section title="Contact">
          <p>
            Questions about this policy or your data can be sent through the
            contact information listed on the{" "}
            <Link
              href="/"
              className="text-sky-300/90 underline decoration-sky-300/30 underline-offset-2 hover:text-sky-200"
            >
              Orbit website
            </Link>{" "}
            or the Chrome Web Store listing support channel once published.
          </p>
        </Section>

        <p className="mt-12 border-t border-white/10 pt-8 text-xs leading-6 text-zinc-600">
          NASA imagery and mission data used in Orbit remain subject to{" "}
          <a
            href="https://www.nasa.gov/nasa-brand-center/images-and-media/"
            className="text-zinc-500 underline underline-offset-2 hover:text-zinc-400"
            rel="noopener noreferrer"
            target="_blank"
          >
            NASA media guidelines
          </a>
          . NASA does not endorse this product.
        </p>
      </article>
    </main>
  );
}
